services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./semantic/backend:/app/backend
    command: >
       /bin/sh -c "python -m poetry run uvicorn backend.main:app --host 0.0.0.0 --port 8000"


  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./semantic/frontend/src:/app/src
      - ./semantic/frontend/public:/app/public
    command: >
        /bin/sh -c "npm start"
