version: "3"

services:
#  backend:
#    build:
#      context: .
#      dockerfile: docker/backend/Dockerfile
#    ports:
#      - "8000:8000"
#    image: backend:latest

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    image: frontend:latest
