FROM node:20.10.0

WORKDIR /app

COPY ../../semantic/frontend/package*.json ./

COPY ../../semantic/frontend .

#RUN npm install

#EXPOSE 3000
#
#CMD ["npm", "run", "build"]
#CMD ["npm", "install", "serve"]

#CMD ["serve", "-s", "build"]
